In [4]:
start_point_for_correct_area = 'this is insane'
end_point_for_correct_area = 'what the fuck'
msg = (f'correct area is from {start_point_for_correct_area}'
        f'to {end_point_for_correct_area}')
print(msg)


correct area is from this is insaneto what the fuck


In [3]:
test = ['abcd', 'dddddd']


a, b = test
print(a)
print(b)

abcd
dddddd


In [38]:
import torch
p = torch.randn([1, 3])
print(p)

prob, idx = torch.max(p, dim=1)
print(prob)
print(idx)

probs, idxs = torch.topk(p, k=2, dim=1)

prob = probs[0][0]
print(prob)


tensor([[-0.0354, -0.0923, -0.0813]])
tensor([-0.0354])
tensor([0])
tensor(-0.0354)


In [17]:
torch.round(torch.tensor([0.1234567]), decimals=3)

TypeError: round() got an unexpected keyword argument 'decimals'