# Face identification

In [5]:
!python main.py --new_user_name "kc"

new_user_name :  kc
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
Using cache found in /Users/KC/.cache/torch/hub/ultralytics_yolov5_master
YOLOv5 🚀 2022-7-1 Python-3.9.12 torch-1.11.0 CPU

Fusing layers... 
YOLOv5s summary: 213 layers, 7225885 parameters, 0 gradients
Adding AutoShape... 

start video capturing
tensor([[0.05698, 0.92129, 0.01400, 0.98970]], grad_fn=<SigmoidBackward0>)
prob: tensor([0.98970], grad_fn=<MaxBackward0>) index: tensor([3])
tensor([[0.02951, 0.40422, 0.04814, 0.99946]], grad_fn=<SigmoidBackward0>)
prob: tensor([0.99946], grad_fn=<MaxBackward0>) index: tensor([3])
tensor([[0.03409, 0.52689, 0.01748, 0.99936]], grad_fn=<SigmoidBackward0>)
prob: tensor([0.99936], grad_fn=<MaxBackward0>) index: tensor([3])
tensor([[0.04070, 0.41450, 0.01820, 0.99835]], grad_fn=<SigmoidBackward0>)
prob: tensor([0.99835], grad_fn=<MaxBackward0>) index: tensor([3])
tensor([[0.04665, 0.67503, 0.03412, 0.99230]], grad_fn=<SigmoidBackward0>)
prob: tensor([0.99230], grad_fn=<M

# Test for Temporary Issues

In [28]:
import json

path_config = "./configs/config.json"
with open(path_config) as f:
  cfg = json.load(f)

In [47]:
from modules.external_library import MTCNN, InceptionResnetV1

import torch
import torch.nn as nn
from torch.nn import functional as F
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = InceptionResnetV1(pretrained='vggface2', classify=True, num_classes=4, device= device)
state = torch.load('./data/face-extraction-model.pt', map_location=device)
model.load_state_dict(state)
model.classify = True
# model = model.to('cpu')
model.eval()

InceptionResnetV1(
  (conv2d_1a): BasicConv2d(
    (conv): Conv2d(3, 32, kernel_size=(3, 3), stride=(2, 2), bias=False)
    (bn): BatchNorm2d(32, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
    (relu): ReLU()
  )
  (conv2d_2a): BasicConv2d(
    (conv): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), bias=False)
    (bn): BatchNorm2d(32, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
    (relu): ReLU()
  )
  (conv2d_2b): BasicConv2d(
    (conv): Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
    (bn): BatchNorm2d(64, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
    (relu): ReLU()
  )
  (maxpool_3a): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
  (conv2d_3b): BasicConv2d(
    (conv): Conv2d(64, 80, kernel_size=(1, 1), stride=(1, 1), bias=False)
    (bn): BatchNorm2d(80, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
    (relu): ReLU()
  )
  (conv2d_4a): 

In [48]:
cfg_face = cfg['FaceAnalyst']
registered_users = cfg_face['registered_users']

In [61]:
from PIL import Image
img = Image.open('./data/photos/jhyoo/1.png')

print(model(img))


TypeError: conv2d() received an invalid combination of arguments - got (PngImageFile, Parameter, NoneType, tuple, tuple, tuple, int), but expected one of:
 * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, tuple of ints padding, tuple of ints dilation, int groups)
      didn't match because some of the arguments have invalid types: (!PngImageFile!, !Parameter!, !NoneType!, !tuple!, !tuple!, !tuple!, int)
 * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, str padding, tuple of ints dilation, int groups)
      didn't match because some of the arguments have invalid types: (!PngImageFile!, !Parameter!, !NoneType!, !tuple!, !tuple!, !tuple!, int)
